name: Run Tests

on:
  push:
    branches:
    - main
    tags:
    - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
  merge_group:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install library
      run: pip install -e ".[dev]" --extra-index-url https://pypi.anaconda.org/lembas-project/simple
    - name: Test with pytest
      run: pytest tests/ -v

  build:
    uses: ./.github/workflows/build.yml

  check:
    if: always()
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether all required jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

  publish:
    uses: ./.github/workflows/publish.yml
    needs: [check]
    secrets: inherit
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.event.ref, 'refs/tags/v') }}
